# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'workout_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_WorkoutDialog(object):
    def setupUi(self, WorkoutDialog):
        WorkoutDialog.setObjectName(_fromUtf8("WorkoutDialog"))
        WorkoutDialog.resize(492, 731)
        self.buttonBox = QtGui.QDialogButtonBox(WorkoutDialog)
        self.buttonBox.setGeometry(QtCore.QRect(140, 690, 340, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayoutWidget = QtGui.QWidget(WorkoutDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 491, 671))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.mainVLayout = QtGui.QVBoxLayout(self.horizontalLayoutWidget)
        self.mainVLayout.setMargin(0)
        self.mainVLayout.setObjectName(_fromUtf8("mainVLayout"))
        self.plannedWGroupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.plannedWGroupBox.setFont(font)
        self.plannedWGroupBox.setFlat(False)
        self.plannedWGroupBox.setCheckable(False)
        self.plannedWGroupBox.setChecked(False)
        self.plannedWGroupBox.setObjectName(_fromUtf8("plannedWGroupBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.plannedWGroupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 471, 311))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayoutPlanned = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutPlanned.setMargin(0)
        self.gridLayoutPlanned.setVerticalSpacing(10)
        self.gridLayoutPlanned.setObjectName(_fromUtf8("gridLayoutPlanned"))
        self.trimpLayoutPlanned = QtGui.QHBoxLayout()
        self.trimpLayoutPlanned.setObjectName(_fromUtf8("trimpLayoutPlanned"))
        self.rpeLabelPlannedW = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rpeLabelPlannedW.setFont(font)
        self.rpeLabelPlannedW.setObjectName(_fromUtf8("rpeLabelPlannedW"))
        self.trimpLayoutPlanned.addWidget(self.rpeLabelPlannedW)
        self.rpeComboBoxPlannedW = QtGui.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rpeComboBoxPlannedW.setFont(font)
        self.rpeComboBoxPlannedW.setObjectName(_fromUtf8("rpeComboBoxPlannedW"))
        self.trimpLayoutPlanned.addWidget(self.rpeComboBoxPlannedW)
        self.trimpLabelPlannedW = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.trimpLabelPlannedW.setFont(font)
        self.trimpLabelPlannedW.setObjectName(_fromUtf8("trimpLabelPlannedW"))
        self.trimpLayoutPlanned.addWidget(self.trimpLabelPlannedW)
        self.trimpLineEditPlannedW = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.trimpLineEditPlannedW.setReadOnly(True)
        self.trimpLineEditPlannedW.setObjectName(_fromUtf8("trimpLineEditPlannedW"))
        self.trimpLayoutPlanned.addWidget(self.trimpLineEditPlannedW)
        self.trimpLayoutPlanned.setStretch(0, 1)
        self.trimpLayoutPlanned.setStretch(1, 8)
        self.trimpLayoutPlanned.setStretch(2, 1)
        self.trimpLayoutPlanned.setStretch(3, 2)
        self.gridLayoutPlanned.addLayout(self.trimpLayoutPlanned, 2, 0, 1, 1)
        self.typeLayoutPlanned = QtGui.QHBoxLayout()
        self.typeLayoutPlanned.setObjectName(_fromUtf8("typeLayoutPlanned"))
        self.typeLabelPlannedW = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.typeLabelPlannedW.setFont(font)
        self.typeLabelPlannedW.setObjectName(_fromUtf8("typeLabelPlannedW"))
        self.typeLayoutPlanned.addWidget(self.typeLabelPlannedW)
        self.typeComboBoxPlannedW = QtGui.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.typeComboBoxPlannedW.setFont(font)
        self.typeComboBoxPlannedW.setObjectName(_fromUtf8("typeComboBoxPlannedW"))
        self.typeLayoutPlanned.addWidget(self.typeComboBoxPlannedW)
        self.durationLabelPlannedW = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.durationLabelPlannedW.setFont(font)
        self.durationLabelPlannedW.setObjectName(_fromUtf8("durationLabelPlannedW"))
        self.typeLayoutPlanned.addWidget(self.durationLabelPlannedW)
        self.durationSpinBoxPlannedW = QtGui.QSpinBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.durationSpinBoxPlannedW.setFont(font)
        self.durationSpinBoxPlannedW.setMaximum(600)
        self.durationSpinBoxPlannedW.setSingleStep(5)
        self.durationSpinBoxPlannedW.setProperty("value", 60)
        self.durationSpinBoxPlannedW.setObjectName(_fromUtf8("durationSpinBoxPlannedW"))
        self.typeLayoutPlanned.addWidget(self.durationSpinBoxPlannedW)
        self.typeLayoutPlanned.setStretch(0, 1)
        self.typeLayoutPlanned.setStretch(1, 8)
        self.gridLayoutPlanned.addLayout(self.typeLayoutPlanned, 1, 0, 1, 1)
        self.descriptionLayoutPlanned = QtGui.QHBoxLayout()
        self.descriptionLayoutPlanned.setObjectName(_fromUtf8("descriptionLayoutPlanned"))
        self.verticalLayoutPlanned = QtGui.QVBoxLayout()
        self.verticalLayoutPlanned.setObjectName(_fromUtf8("verticalLayoutPlanned"))
        self.descriptionLabelPlannedW = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.descriptionLabelPlannedW.setFont(font)
        self.descriptionLabelPlannedW.setObjectName(_fromUtf8("descriptionLabelPlannedW"))
        self.verticalLayoutPlanned.addWidget(self.descriptionLabelPlannedW)
        self.descriptionTextEditPlannedW = QtGui.QTextEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descriptionTextEditPlannedW.setFont(font)
        self.descriptionTextEditPlannedW.setFrameShadow(QtGui.QFrame.Sunken)
        self.descriptionTextEditPlannedW.setObjectName(_fromUtf8("descriptionTextEditPlannedW"))
        self.verticalLayoutPlanned.addWidget(self.descriptionTextEditPlannedW)
        self.verticalLayoutPlanned.setStretch(0, 1)
        self.verticalLayoutPlanned.setStretch(1, 7)
        self.descriptionLayoutPlanned.addLayout(self.verticalLayoutPlanned)
        self.gridLayoutPlanned.addLayout(self.descriptionLayoutPlanned, 3, 0, 1, 1)
        self.gridLayoutWidget_2.raise_()
        self.mainVLayout.addWidget(self.plannedWGroupBox)
        self.actualWGroupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.actualWGroupBox.setObjectName(_fromUtf8("actualWGroupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.actualWGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 471, 271))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayoutActual = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutActual.setMargin(0)
        self.gridLayoutActual.setVerticalSpacing(10)
        self.gridLayoutActual.setObjectName(_fromUtf8("gridLayoutActual"))
        self.descriptionLayoutActual = QtGui.QHBoxLayout()
        self.descriptionLayoutActual.setObjectName(_fromUtf8("descriptionLayoutActual"))
        self.verticalLayoutActual = QtGui.QVBoxLayout()
        self.verticalLayoutActual.setObjectName(_fromUtf8("verticalLayoutActual"))
        self.descriptionLabelActual = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.descriptionLabelActual.setFont(font)
        self.descriptionLabelActual.setObjectName(_fromUtf8("descriptionLabelActual"))
        self.verticalLayoutActual.addWidget(self.descriptionLabelActual)
        self.descriptionTextEditActual = QtGui.QTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descriptionTextEditActual.setFont(font)
        self.descriptionTextEditActual.setFrameShadow(QtGui.QFrame.Sunken)
        self.descriptionTextEditActual.setObjectName(_fromUtf8("descriptionTextEditActual"))
        self.verticalLayoutActual.addWidget(self.descriptionTextEditActual)
        self.verticalLayoutActual.setStretch(0, 1)
        self.descriptionLayoutActual.addLayout(self.verticalLayoutActual)
        self.gridLayoutActual.addLayout(self.descriptionLayoutActual, 2, 0, 1, 1)
        self.typeLayoutActual = QtGui.QHBoxLayout()
        self.typeLayoutActual.setObjectName(_fromUtf8("typeLayoutActual"))
        self.typeLabelActualW = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.typeLabelActualW.setFont(font)
        self.typeLabelActualW.setObjectName(_fromUtf8("typeLabelActualW"))
        self.typeLayoutActual.addWidget(self.typeLabelActualW)
        self.typeComboBoxActualW = QtGui.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.typeComboBoxActualW.setFont(font)
        self.typeComboBoxActualW.setObjectName(_fromUtf8("typeComboBoxActualW"))
        self.typeLayoutActual.addWidget(self.typeComboBoxActualW)
        self.durationLabelActualW = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.durationLabelActualW.setFont(font)
        self.durationLabelActualW.setObjectName(_fromUtf8("durationLabelActualW"))
        self.typeLayoutActual.addWidget(self.durationLabelActualW)
        self.durationSpinBoxActualW = QtGui.QSpinBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.durationSpinBoxActualW.setFont(font)
        self.durationSpinBoxActualW.setMaximum(600)
        self.durationSpinBoxActualW.setSingleStep(5)
        self.durationSpinBoxActualW.setProperty("value", 60)
        self.durationSpinBoxActualW.setObjectName(_fromUtf8("durationSpinBoxActualW"))
        self.typeLayoutActual.addWidget(self.durationSpinBoxActualW)
        self.typeLayoutActual.setStretch(0, 1)
        self.typeLayoutActual.setStretch(1, 8)
        self.gridLayoutActual.addLayout(self.typeLayoutActual, 0, 0, 1, 1)
        self.trimpLayoutActual = QtGui.QHBoxLayout()
        self.trimpLayoutActual.setObjectName(_fromUtf8("trimpLayoutActual"))
        self.rpeLabelActualW = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rpeLabelActualW.setFont(font)
        self.rpeLabelActualW.setObjectName(_fromUtf8("rpeLabelActualW"))
        self.trimpLayoutActual.addWidget(self.rpeLabelActualW)
        self.rpeComboBoxActualW = QtGui.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rpeComboBoxActualW.setFont(font)
        self.rpeComboBoxActualW.setObjectName(_fromUtf8("rpeComboBoxActualW"))
        self.trimpLayoutActual.addWidget(self.rpeComboBoxActualW)
        self.trimpLabelActualW = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.trimpLabelActualW.setFont(font)
        self.trimpLabelActualW.setObjectName(_fromUtf8("trimpLabelActualW"))
        self.trimpLayoutActual.addWidget(self.trimpLabelActualW)
        self.trimpLineEditActualW = QtGui.QLineEdit(self.gridLayoutWidget)
        self.trimpLineEditActualW.setReadOnly(True)
        self.trimpLineEditActualW.setObjectName(_fromUtf8("trimpLineEditActualW"))
        self.trimpLayoutActual.addWidget(self.trimpLineEditActualW)
        self.trimpLayoutActual.setStretch(0, 1)
        self.trimpLayoutActual.setStretch(1, 8)
        self.trimpLayoutActual.setStretch(2, 1)
        self.trimpLayoutActual.setStretch(3, 2)
        self.gridLayoutActual.addLayout(self.trimpLayoutActual, 1, 0, 1, 1)
        self.mainVLayout.addWidget(self.actualWGroupBox)
        self.mainVLayout.setStretch(0, 41)
        self.mainVLayout.setStretch(1, 37)

        self.retranslateUi(WorkoutDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), WorkoutDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), WorkoutDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(WorkoutDialog)

    def retranslateUi(self, WorkoutDialog):
        WorkoutDialog.setWindowTitle(_translate("WorkoutDialog", "Workout", None))
        self.plannedWGroupBox.setTitle(_translate("WorkoutDialog", "Planned Workout", None))
        self.rpeLabelPlannedW.setText(_translate("WorkoutDialog", "RPE: ", None))
        self.trimpLabelPlannedW.setText(_translate("WorkoutDialog", "TRIMP: ", None))
        self.typeLabelPlannedW.setText(_translate("WorkoutDialog", "Type: ", None))
        self.durationLabelPlannedW.setText(_translate("WorkoutDialog", "Duration: ", None))
        self.descriptionLabelPlannedW.setText(_translate("WorkoutDialog", "Description:", None))
        self.actualWGroupBox.setTitle(_translate("WorkoutDialog", "Actual Workout", None))
        self.descriptionLabelActual.setText(_translate("WorkoutDialog", "Description:", None))
        self.typeLabelActualW.setText(_translate("WorkoutDialog", "Type: ", None))
        self.durationLabelActualW.setText(_translate("WorkoutDialog", "Duration: ", None))
        self.rpeLabelActualW.setText(_translate("WorkoutDialog", "RPE: ", None))
        self.trimpLabelActualW.setText(_translate("WorkoutDialog", "TRIMP: ", None))

